
exclude:
 
 
   - fqbn:
      - arduino:renesas_uno:minima
      - arduino:renesas_uno:unor4wifi
      - arduino:samd:mkrzero
      - infineon:psoc6:cy8ckit_062s2_ai
      - Infineon:xmc:XMC1400_XMC2GO
      - Infineon:xmc:XMC1100_XMC2GO